---
driver:
  name: terraform
  root_module_directory: test/fixtures/tf_module
  parallelism: 4

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: local
      controls:
        - file_check_external_provider
        - external_ip
        - state_file

platforms:
  - name: terraform

suites:
  - name: kt_suite





